### ISSUE TITLE
Understand Discuss Hangul routine

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/EsoKR#1]
@dohyunkim You and I have never met. I found your name trying to google for help with Lua and Hangul font.

I am wondering if you would be willing to help explain some things about the code I am working with. I am not the original author of the code so I do not understand what it is doing.

I work on various Lua modifications for a game called Elder Scrolls Online. I only speak English and Spanish. I am trying to help a team of people that use an unofficial Korean translation of the game. 

# Problem

When typing in chat for the game the Hangul font is a multi byte sequence and the game uses a single byte sequence. For this reason the previous author altered the text slightly. I do not understand what he was doing. The reason the Korean users asked for my help is because when they delete one character then the game will crash.

# Relevant code
[Raw Code](https://github.com/ESOUIMods/EsoKR/blob/main/EsoKR.lua#L109-L118)
```Lua
  if temp >= 0xE18480 and temp <= 0xE187BF then temp = temp + 0x43400
  elseif temp > 0xE384B0 and temp <= 0xE384BF then temp = temp + 0x237D0
  elseif temp > 0xE38580 and temp <= 0xE3868F then temp = temp + 0x23710
  elseif temp >= 0xEAB080 and temp <= 0xED9EAC then
      if temp >= 0xEAB880 and temp <= 0xEABFBF then temp = temp - 0x33800
          elseif temp >= 0xEBB880 and temp <= 0xEBBFBF then temp = temp - 0x33800
          elseif temp >= 0xECB880 and temp <= 0xECBFBF then temp = temp - 0x33800
          else temp = temp - 0x3F800
      end
  elseif not encode and temp >= 0xE6B880 and temp <= 0xE9A6A3 then temp = temp + 0x3F800
  end
```

# Question

Why would the previous author do that, what are the extra characters (0x43400, 0x237D0, 0x23710, 0x33800) added depending on the range?

**Comment by Sharlikran** [comment]
# Observation

When using a [virtual machine ](https://www.tutorialspoint.com/execute_lua_online.php) I was able to get the output of `con2CNKR()` and the string is displayed in the Firefox incorrectly.

Original String: `안녕하세요 경기장에 오신 것을 환영합니다`
With `con2CNKR()`: 
![image](https://user-images.githubusercontent.com/1912426/125339323-0a79de80-e306-11eb-80f5-2a1817ad605e.png)

[KoreanTesting.zip](https://github.com/ESOUIMods/EsoKR/files/6803689/KoreanTesting.zip)

**Comment by Sharlikran** [comment]
한국어만 하시면 "Google Translate" 웹사이트를 사용하겠습니다.

**Comment by dohyunkim** [comment]
I also do not have much idea about the code, but it seems to be related to the special fonts you provide under `fonts` directory.

For instance, `가` (U+AC00) is `0xEA 0xB0 0x80` in UTF-8 byte sequence, which will be converted to 0x6E00 by `con2CNKR()` function. BTW the glyph 0x6E00 in ftn47.otf under `fonts` directory is '가'-shaped as the attached image shows.
[ftn47-GA.pdf](https://github.com/ESOUIMods/EsoKR/files/6804971/ftn47-GA.pdf)

**Comment by Sharlikran** [comment]
You obviously have have more knowledge then me of the language. Thank you for discussing this with me.

When you said that 가 (U+AC00) then I looked again at a webpage I found. [Decision string (UTF-8 encoding) is a Chinese, Korean, Japanese LUA implementation](https://www.programmersought.com/article/47458951553/) and on that web page in the code comments it says that (0xAC00 -- 0xD7AF) are Hangul Syllables.

Then I read your response that con2CNKR() is converting the value to 0x6E00 which I do not see how you figured that out.

However, I opened univers57.otf in FontForge and saw this

![image](https://user-images.githubusercontent.com/1912426/125389102-894a3800-e355-11eb-9937-6df8ac6e0e87.png)
![image](https://user-images.githubusercontent.com/1912426/125389141-9830ea80-e355-11eb-8ab0-9fa65753487c.png)

Then FontForge would not open SourceHanSansK-Regular.otf from [this link](https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R)

So I went to [a website](https://torinak.com/font/lsfont.html) to look at the font.

![image](https://user-images.githubusercontent.com/1912426/125389859-b77c4780-e356-11eb-9469-407a37aa78cc.png)

That font has the Glyph at AC00 rather then 6E00

Thank you so much for your help and insight I think I have something to work on now.

좋은 하루 되세요

**Comment by dohyunkim** [comment]
Your screenshot of U+6E00 is different to mine. 
<img width="740" alt="스크린샷 2021-07-13 오후 5 08 15" src="https://user-images.githubusercontent.com/4328134/125415829-2e407dae-d389-4796-b79d-3f598b7e69a0.png">
U+6E00 is a Chinese Ideorgraphic character, not Hangul. 
If you use a standard-observing font instead of the fonts under `fonts` directory, you'll see `渀` instead of `가`. 
So when you use a standard-observing font in your application, I bet you may live without `con2CNKR()` routine.

**Comment by harion01** [comment]
Hello, I'm one of the ESOKR developer. Thanks so much for discussing about the issue. 

ESO KR addon was not my part. but I know the background history.

Prob : 
When typing in chat for the game the Hangul font is a multi byte sequence and the game uses a single byte sequence. For this reason the previous author altered the text slightly. I do not understand what he was doing. The reason the Korean users asked for my help is because when they delete one character then the game will crash.

Reason :
We didn't notice there is supportable korean unicode in ESO client.
So we decide to use useless range of chinese unicode instead

**Comment by Sharlikran** [comment]
@harion01 I have been investigating this for days trying to figure out why `con2CNKR()` was changing the byte offset of the text. I am so glad I found dohyunkim and I am very grateful for his insight into the matter. He noticed instantly that the Glyphs were in the U+6E00 range for Chinese and not U+AC00 for Hangul.

I see now that you were forced to use the non-standard range for Chinese because the game does not support the proper range for Hangul.

I have reported this to ZOS but I have no idea what will happen.

**Comment by Sharlikran** [comment]
ZOSDanBatson
```Lua
    -- (0x2E80 -- 0x2FDF) -- CJK Radicals Supplement & Kangxi Radicals
    -- (0x2FF0 -- 0x30FF) -- Ideographic Description Characters, CJK Symbols and Punctuation & Japanese
    -- (0x3100 -- 0x31BF) -- Korean
    -- (0x31C0 -- 0x4DFF) -- Other extensions
    -- (0x4E00 -- 0x9FBF) -- CJK Unified Ideographs
    -- (0xAC00 -- 0xD7AF) -- Hangul Syllables
    -- (0xF900 -- 0xFAFF) -- CJK Compatibility Ideographs
    -- (0xFE30 -- 0xFE4F) -- CJK Compatibility Forms
```
So why ESO does not allow using (0xAC00 -- 0xD7AF) I don't know. However, if that can be addressed then the Korean team could use a standard font and would not need to change the Byte offset of the characters to use the Chinese Ideograph Unicode Space.

The above numbers (0xAC00 -- 0xD7AF)  correlate to the screen shots of the font. The three byte sequence for the Glyphs themselves are different.
![image](https://user-images.githubusercontent.com/1912426/125469802-1640980d-10d3-4cfc-a9dc-50cfe2de1ce8.png)
Byte Sequence: E6B880 
![image](https://user-images.githubusercontent.com/1912426/125469922-949484a2-cbc7-4680-bef4-ac7ff45253e0.png)
Byte Sequence: EAB080

**Comment by Sharlikran** [comment]
Input a single char, be it a one byte sequence like English `abcde` or a multi-byte sequence 가.
Returns True or False of it is Chinese, Japanese, or Korean characters
```lua
function isCJKCode(char)
    local len = string.len(char)
    local chInt = 0
    for i = 1, len do
        local n = string.byte(char, i)
        chInt = chInt * 256 + n
    end
    -- (0x2E80 -- 0x2FDF) -- CJK Radicals Supplement & Kangxi Radicals
    -- (0x2FF0 -- 0x30FF) -- Ideographic Description Characters, CJK Symbols and Punctuation & Japanese
    -- (0x3100 -- 0x31BF) -- Korean
    -- (0x31C0 -- 0x4DFF) -- Other extensions
    -- (0x4E00 -- 0x9FBF) -- CJK Unified Ideographs
    -- (0xAC00 -- 0xD7AF) -- Hangul Syllables
    -- (0xF900 -- 0xFAFF) -- CJK Compatibility Ideographs
    -- (0xFE30 -- 0xFE4F) -- CJK Compatibility Forms
    return (chInt >= 14858880 and chInt <= 14860191)
        or (chInt >= 14860208 and chInt <= 14910399)
        or (chInt >= 14910592 and chInt <= 14911167)
        or (chInt >= 14911360 and chInt <= 14989247)
        or (chInt >= 14989440 and chInt <= 15318719) -- (0x4E00 -- 0x9FBF) CJK Unified Ideographs
        or (chInt >= 15380608 and chInt <= 15572655) -- (0xAC00 -- 0xD7AF) Hangul
        or (chInt >= 15705216 and chInt <= 15707071)
        or (chInt >= 15710384 and chInt <= 15710607)
end
```
Variation of stringToChars() from this link: [Decision string (UTF-8 encoding) is a Chinese, Korean, Japanese LUA implementation](https://www.programmersought.com/article/47458951553/)
```lua
function stringToChars(str)
    local list = {}
    local len = string.len(str)
    local i = 1
    while i <= len do
        local c = string.byte(str, i)
        local shift = 1
        if c > 0 and c <= 127 then
            shift = 1
        elseif (c >= 192 and c <= 223) then
            shift = 2
        elseif (c >= 224 and c <= 239) then
            shift = 3
        elseif (c >= 240 and c <= 247) then
            shift = 4
        end
        local char = string.sub(str, i, i+shift-1)
        i = i + shift
        table.insert(list, char)
    end
    return list, table.concat(list), len
end
```
The variation adds table.concat() so that I would have the entire string of Glyphs rather then a table.

**Comment by Sharlikran** [comment]
@harion01 [https://www.esoui.com/forums/showthr...5859#post45859](https://www.esoui.com/forums/showthread.php?p=45859#post45859)

If you know of anybody that has been wanting to help update EsoKR please ask them to post in that thread.

**Comment by harion01** [comment]
Hello Sharlikran, Thanks helping Korean translation. For now, I’m not focusing on translation work. But there is good news in Korean translation team. We rebuild our translation homepage and also make some communication discord channel. http://worldwideweirdo.iptime.org:65532/eso/translateList.php https://discord.com/invite/36uQza9eEG Also, they know you are looking for contributors.  Hope you find good coworker in your journey 😊 Have a nice day.   보낸 사람: Sharlikran보낸 날짜: 2022년 5월 7일 토요일 오전 8:56받는 사람: ESOUIMods/EsoKR참조: harion01; Mention제목: Re: [ESOUIMods/EsoKR] Understand Discuss Hangul routine ***@***.*** https://www.esoui.com/forums/showthr...5859#post45859If you know of anybody that has been wanting to help update EsoKR please ask them to post in that thread.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
