### ISSUE TITLE
Update EsoKR

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/EsoKR#2]
@harion01 Whya5448 is not available to keep EsoKR up to date. I have added my changes to the new version 10.00. I am wondering if there are other versions not available from ESOUI that I can download and look at the changes?

Whya5448은 EsoKR을 최신 상태로 유지하는 데 사용할 수 없습니다. 새 버전 10.00에 변경 사항을 추가했습니다. ESOUI에서 다운로드하여 변경 사항을 볼 수 없는 다른 버전이 있는지 궁금합니다.

**Comment by harion01** [comment]
I'll check the final version and notify. Thanks for helping us :)

**Comment by harion01** [comment]
@Sharlikran It seems there no more changes in ESOKR with in version control system. Most of Korean users are using the ESOKR addon in ESOUI site. If you need more modify, just keep it update to ESOUI site. Again, thanks for helping us.

**Comment by Sharlikran** [comment]
@harion01 There is a very dire situation. @dedo2 has taken down "netadm83.iptime.org" the original ESOKR_AutoPatch will auto delete the files when the process is complete. However, if @dedo2 is no longer going to offer the site, and I can not download the files there is no way to make an entire new translation.

매우 심각한 상황이 있습니다. "@dedo2"가 "netadm83.iptime.org"를 삭제했습니다. 원래 "ESOKR_AutoPatch"는 프로세스가 완료되면 파일을 자동으로 삭제합니다. 그러나 "@dedo2"가 더 이상 사이트를 제공하지 않고 파일을 다운로드할 수 없는 경우 완전히 새로운 번역을 만들 수 있는 방법이 없습니다.

Can you help me get those files please?

그 파일들을 구할 수 있게 도와주시겠습니까?

Required Files, these I must have / 필수 파일, 이것들은 내가 가지고 있어야합니다

kr.lang.txt
kr.lang.id.txt
kb.lang.txt
kb.lang.id.txt

Required but maybe can do without / 필수이지만 아마도 없이 할 수 있습니다.

kr_client.str
kr_pregame.str
kb_client.str
kb_pregame.str

**Comment by harion01** [comment]
@Sharlikran I always thanks for your attention. let me share the architecture of our translation system first.
![translation](https://user-images.githubusercontent.com/9984967/134952173-1fd78822-1911-461c-b910-bac4857bf177.PNG)

**Comment by harion01** [comment]
@Sharlikran With that kind of system, we always need someone to maintain translation server. It is hard work to keep operating this system. I was one of developer who made the system. But I also gave up to maintain the system and let dedo maintain it - he gave it up too.

So, it is not just matter of updating addon but also matter of the Korean translation community.

The problem is not system. we lost all of developer who want to maintain the system - including me. 

In my opinion, broken system is also one of motivation of developer - like you.

It seems like endless cycle of pain. we keep try to fix bug and update ESO data without support of ZOS again and again. 

So I really hesitate to share this system to you. It is really time consuming job,

**Comment by Sharlikran** [comment]
Thank you for sharing your previous method, I understand the complexities and concerns in maintaining it. However, at this point I am looking for copies of the files I mentioned.

Required Files, these I must have / 필수 파일, 이것들은 내가 가지고 있어야합니다

kr.lang.txt
kr.lang.id.txt
kb.lang.txt
kb.lang.id.txt

Really I need them from any source. I wish I could get them from dedo2 himself but that is why I am asking for your help. I have tried to contact him can you also try please?

If I can get those 4 files I at least have a way to do something.

**Comment by Sharlikran** [comment]
Unfortunately the software for the Chinese translation communicates with a server and the author didn't plan on having the software available for other languages. That software is no longer an option.

**Comment by Sharlikran** [comment]
@harion01 I think I have a way to translate some more Korean text. If I do though, how do you convert the text from traditional Hangul into Chinese UTF8, did you use an EXE?

Because if volunteers translate the text it will be using traditional font. There is really no other way. How do I convert it so that once in game and using the non standard font everything will show up properly?
